local_sources := syscall.c \
				 sys_execve.c \
				 sys_exit.c \
				 sys_fork.c \
				 sys_fstat.c \
				 sys_getpid.c \
				 sys_getppid.c \
				 sys_getuid.c \
				 sys_getgid.c \
				 sys_getpgid.c \
				 sys_setpgid.c \
				 sys_tcgetpgrp.c \
				 sys_tcsetpgrp.c \
				 sys_getcwd.c \
				 sys_info.c \
				 sys_nanosleep.c \
				 sys_mknod.c \
				 sys_open.c \
				 sys_close.c \
				 sys_lseek.c \
				 sys_dup.c \
				 sys_dup2.c \
				 sys_read.c \
				 sys_sbrk.c \
				 sys_setgid.c \
				 sys_setuid.c \
				 sys_waitpid.c \
				 sys_write.c \
				 sys_sigaction.c \
				 sys_sigreturn.c \
				 sys_sigsuspend.c \
				 sys_kill.c \
				 sys_sigprocmask.c \
				 sys_pipe.c \
				 sys_chdir.c \
				 sys_alarm.c \
				 sys_mount.c \
				 sys_clock.c

