local_sources := FILE.c \
				 fopen.c \
				 fdopen.c \
				 fclose.c \
				 fread.c \
				 fwrite.c \
				 ferror.c \
				 feof.c \
				 fflush.c \
				 fputc.c \
				 putchar.c \
				 fputs.c \
				 puts.c \
				 fgetc.c \
				 getchar.c \
				 fgets.c \
				 gets.c \
				 perror.c \
				 printf.c \
				 sprintf.c \
				 snprintf.c \
				 vprintf.c \
				 vsprintf.c \
				 vsnprintf.c \
				 fprintf.c \
				 vfprintf.c \
				 popen.c \
				 pclose.c \
				 fileno.c
